application: click-in
version: 1
runtime: python
api_version: 1

handlers:
- url: /html
  static_dir: html
  
- url: /stylesheets
  static_dir: stylesheets
  
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /.*
  script: main.py
