application: clickin-tech
version: 1
runtime: python
api_version: 1

handlers: 
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: /stylesheets
  static_dir: stylesheets
  
- url: /js
  static_dir: js 
  
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /search
  script: main.py
  login: required

- url: /.*
  script: main.py
 
builtins:
- remote_api: on
