application: click-in
version: 1
runtime: python
api_version: 1

handlers: 
- url: /stylesheets
  static_dir: stylesheets
  
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /search
  script: main.py
  login: required

- url: /.*
  script: main.py
